# Background and foreground colors
background = #0b0b0c
foreground = #fcf6de

# Standard colors
palette = 0=#0b0b0c
palette = 1=#ff4a14
palette = 2=#FBE266
palette = 3=#FED32B
palette = 4=#fc855a
palette = 5=#fe9267
palette = 6=#f7c67d
palette = 7=#EFDB8F

# Bright colors
palette = 8=#9c7160
palette = 9=#ffa085
palette = 10=#fff4be
palette = 11=#ffe686
palette = 12=#ffc7b3
palette = 13=#ffd3c2
palette = 14=#feecd1
palette = 15=#fcf6de
