background            #0b0b0c
foreground            #fcf6de

# black
color0  #0b0b0c
color8  #9c7160

# red
color1  #ff4a14
color9  #ffa085

# green
color2  #FBE266
color10 #fff4be

# yellow
color3  #FED32B
color11 #ffe686

# blue
color4  #fc855a
color12 #ffc7b3

# magenta
color5  #fe9267
color13 #ffd3c2

#cyan
color6  #f7c67d
color14 #feecd1

#white
color7  #EFDB8F
color15 #fcf6de


